#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Auto-fix linting issues
npm run lint:fix
# Auto-fix prettier formatting issues
npx prettier --write "**/*.{ts,js,json,html,scss,md}"
# Add any formatted files to the commit
git add -A
